### ISSUE TITLE
Blame Eurovision 

### ISSUE THREAD

**Issue by sec122** [pulibrary/RDOS_Publishing#20]
### Faux Ticket against GitHub FOMO 

**I sure hope this is all fine...but what a time to find out!**

The movie shown below is a fictitious story, but if you want a great actual Icelandic song contest entry, see [this](https://youtu.be/VFZNvj-HfBU). 

## Here is a movie available on Netflix

![image](https://user-images.githubusercontent.com/60932884/211408823-f4bb159f-375c-42b1-8598-5ee27654ce79.png)

## Acceptance Criteria: 

- [ ] Watch the Movie
- [ ] Fall in love with Eurovision Song Contest
- [ ] Watch the Grand Finale in the Spring

**Comment by hhkitsune** [comment]
Note: Practice Ticket for Sarah

**Comment by hhkitsune** [comment]
Closing but keeping : )
