### ISSUE TITLE
(PPPL) Needs ARK to resolve to collections page

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/RDOS_Publishing#23]
## Description

PPPL researchers have provided some of their publications with the ARK for a collections page, rather than the specific object's ARK. The ARK for the collection pages in DataSpace will need to be preserved and resolve correctly for PDC Discovery.

## Example

Here is the page for [PPPL, Plasma Science and Technology](https://dataspace.princeton.edu/handle/88435/dsp01x920g025r).

The ARK from this collection page in DataSpace should resolve to the corresponding collection in Discovery, which is [PPPL, Plasma Science and Technology](https://datacommons.princeton.edu/discovery/?f%5Bcollection_name_ssi%5D%5B%5D=Plasma+Science+%26+Technology&f%5Bcommunity_root_name_ssi%5D%5B%5D=Princeton+Plasma+Physics+Laboratory)

**Comment by astrochun** [comment]
I've started to do an audit and it's available [here](https://docs.google.com/spreadsheets/d/1D0z4xQsLqAZQPJtSjOdn81u25siaCU3u3Fn93r-0vyA/edit#gid=1032867214).

Also, should we move this ticket to pdc_discovery?
